### ISSUE TITLE
Time series ortho importing crashing

### ISSUE THREAD

**Issue by volpatoo** [NEPEM-UFSC/plimanshiny#4]
Plimanshiny is crashing when trying to import orthomosaic using Time series module:
It seems the module is not able to find the correct path when importing.

```r
Warning: C:/Orthos/.tif: No such file or directory (GDAL error 4)
Warning: Error in : [rast] file does not exist: C:/Orthos/.tif
  5: runApp
  4: print.shiny.appobj
  2: with_golem_options
  1: run_app
```
![image](https://github.com/user-attachments/assets/923af672-7f1e-4e89-a40b-23d014e5dfb4)

**Comment by TiagoOlivoto** [comment]
Hi @volpatoo .
Did you searched the raster file using the button "Raster Files" and then clicked on "Import"? Note that some specific name patterns must be used, like YYYYDDMM or DDMMYYYY or DD-MM-YYYY or MM-DD-YYYY.
